### ISSUE TITLE
Problems mounting home with encfs 1.9.1

### ISSUE THREAD

**Issue by gcala** [vgough/encfs#261]
Hi, sorry for cross-posting an issue but on archlinux forum [1] I received no help.

The problem summoned updating a laptop with home encrypted through encfs. I used it a few months ago, when encfs was at version 1.8.1. I also installed pam_encfs [2] and kwallet-pam [3] to decrypt/login with the same password. All was fine. The previous week I booted the laptop, it worked as usual; I full-upgraded the system, including encfs-1.9.1. After a reboot and login as usual, kde is unable to load: it shows errors regarding missing configuration files. Seems that initially the home is decrypted/mounted but right after it is unmounted preventing kde to complete boot process. Login from terminal works as expected. The only solution I found was to downgrade to encfs-1.8.1.

This is my setup:

**/etc/pam.d/system-login**

```
#%PAM-1.0

auth       required   pam_tally.so         onerr=succeed file=/var/log/faillog
auth       required   pam_shells.so
auth       requisite  pam_nologin.so
auth	   sufficient pam_encfs.so
auth       include    system-auth

account    required   pam_access.so
account    required   pam_nologin.so
account    include    system-auth

password   include    system-auth

session    optional   pam_loginuid.so
session    include    system-auth
session    optional   pam_motd.so          motd=/etc/motd
session    optional   pam_mail.so          dir=/var/spool/mail standard quiet
-session   optional   pam_systemd.so
session    required   pam_env.so
```

**/etc/pam.d/login**

```
#%PAM-1.0

auth       required     pam_securetty.so
auth       requisite    pam_nologin.so
auth       include      system-local-login
account    include      system-local-login
session    include      system-local-login
session    required     pam_encfs.so
```

**/etc/pam.d/sddm**

```
#%PAM-1.0

auth		include		system-login
auth            sufficient      pam_encfs.so
account		include		system-login
password	include		system-login
session		include		system-login
session         required        pam_encfs.so

auth		optional	pam_kwallet.so  kdehome=.kde4
session		optional	pam_kwallet.so  kdehome=.kde4
auth		optional	pam_kwallet5.so
session		optional	pam_kwallet5.so
```

**/etc/security/pam_encfs.conf**

```
drop_permissions
encfs_default --idle=1
fuse_default nonempty
gcala	/home/.gcala	/home/gcala	-v	allow_other
```

**/etc/fuse.conf**

```
user_allow_other
```

Any idea about the problem? Very thanks.

[1] https://bbs.archlinux.org/viewtopic.php?id=221377
[2] https://code.google.com/archive/p/pam-encfs/
[3] https://cgit.kde.org/kwallet-pam.git/

**Comment by benrubson** [comment]
See #263 ?

**Comment by gcala** [comment]
sorry for my delayed answear. I read #263 and tryed changing /etc/security/pam_encfs.conf with the following lines:

```
encfs_default --no-default-flags
fuse_default use_ino,nonempty
```

Initially, it looked as was the right solution, until I start chrome: it starts for a couple of seconds then quits and with it all my kde session. Seems that only chrome triggers this issue; i tryed chromium, vivaldi, steam, kdevelop, etc without any hassle.

Unfortunately, some time happens that the problem pops just after the login, without triggering chrome.

I returned to encfs 1.8.1 for stability.

Thanks

**Comment by benrubson** [comment]
Could also be related to #214 / #244.

**Comment by benrubson** [comment]
@gcala #214 / #244 should now be solved, would you give master branch a test and close this issue if solved ?
Thank you 👍

**Comment by gcala** [comment]
sorry for my delayed answear, unfortunately last commits didn't solve my issues

**Comment by benrubson** [comment]
Perhaps you are facing the same bug as in #214.
As proposed there to @m13253, could you test this version ?
`git clone -b test214 https://github.com/benrubson/encfs.git`
So that we would be sure easylogging++ is not the cause.
Many thx 👍

**Comment by rfjakob** [comment]
Ok look like #214, let's continue there.
